baseURL = 'https://pjtatlow.dev/'
languageCode = 'en-us'
title = "pjtatlow.dev"

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30


[markup]
  [markup.highlight]
    style = 'catppuccin-mocha'
    tabWidth = 4
